name = "wplace-pixel-tool"
compatibility_date = "2024-01-01"

[site]
bucket = "./out"

# Build configuration for Cloudflare Pages
[[pages_build_output_dir]]
output_dir = "out"

# Custom build settings
[build]
command = "npm run build"
publish = "out"

# Environment variables for production
[env.production]
NODE_ENV = "production"

# Custom headers for better SEO and performance
[[headers]]
for = "/sitemap*.xml"
  [headers.values]
  Content-Type = "application/xml"
  Cache-Control = "public, max-age=3600"

[[headers]]
for = "/robots.txt"
  [headers.values]
  Content-Type = "text/plain"
  Cache-Control = "public, max-age=3600"

[[headers]]
for = "/*.js"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable" 